### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by ck-amrahd** [xingyaoww/LeTI#1]
Hi guys,
I am trying to reproduce the results in my local environment. I am specifically interested in the evaluation of the human eval dataset. Can you please tell me where can I download your checkpoints and reproduce the results (without training)? Thank you.

**Comment by xingyaoww** [comment]
Hi,

Thanks for reaching out! Can you check [this link](https://huggingface.co/xingyaoww/LeTI) to see if you can download the checkpoints to reproduce the evaluation?
