### ISSUE TITLE
t5x checkpoints

### ISSUE THREAD

**Issue by ck-amrahd** [xingyaoww/LeTI#2]
Hi guys,
I am trying to replicate the results for comparison. I see that for creating t5x checkpoints from the hugging face model, you have a script for that. It has a lot of gs paths and I am trying to run it locally. I can change the code but it's cumbersome. Is it possible to provide these checkpoints? Thank you.

**Comment by xingyaoww** [comment]
Thanks for pointing that out! I've add a link to the checkpoints -- see [here](https://github.com/xingyaoww/LeTI/issues/1).
